### ISSUE TITLE
Non-windows platform: Fail build/install if Node Pipe does not exist

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#1165]
~Instead of checking for a non-windows OS, check for the presence of the node-pipe package before using it with zqd.~

Non-windows platform require optional module `node-pipe` to ensure zqd is shutdown in the event brim getting SIGKILL'd. If for some reason node-pipe cannot be installed on a non-windows platform, we only find out about this when a user tries to startup a built copy of brim and the process fails when loading a non-existent node-pipe module.

Instead the either the build process or npm install should fail if `node-pipe` cannot be installed on a non-windows platform.

**Comment by philrz** [comment]
This may become unnecessary depending on how we implement the other fixes proposed in #534. Keeping it around until that's a definite.

**Comment by philrz** [comment]
Indeed, it looks like we have consensus on moving forward with a replacement to `node-pipe` that's now tracked in #2884. Will plan to close this issue once that's implemented.
