### ISSUE TITLE
Can't npm start on Linux, error: "System limit for number of file watchers reached"

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#1755]
Repro is on Ubuntu 18.04 with Node.js `v12.22.3` and NPM `6.14.13`.

I'm not able to run current Brim (such as commit 3e4c700) in Dev mode. As shown in the attached video, after I run `npm start`, the console is flooded with messages similar to this one:

```
Error: ENOSPC: System limit for number of file watchers reached, watch 'node_modules/prop-types-exact/install-relevant-react.sh'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/phil/brim/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/phil/brim/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/phil/brim/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/phil/brim/node_modules/chokidar/lib/nodefs-handler.js:262:21)
    at FSWatcher.<anonymous> (/home/phil/brim/node_modules/chokidar/lib/nodefs-handler.js:495:21)
    at FSReqCallback.oncomplete (fs.js:169:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: 'node_modules/prop-types-exact/install-relevant-react.sh',
  filename: 'node_modules/prop-types-exact/install-relevant-react.sh'
}
```

https://user-images.githubusercontent.com/5934157/126406434-bce42446-2418-451d-b421-24049190a65b.mp4

As shown, if I wait the ~40 seconds for all of the messages to stop accumulating, the app is effectively unusable, as showed by the failed attempt to import a small pcap.

I did some hunting and found [this StackOverflow post](https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve) which advocates working around the problem by increasing the sysctl setting for `fs.inotify.max_user_watches`. Indeed, this next video shows that workaround is effective.

https://user-images.githubusercontent.com/5934157/126406573-e6b56ffd-1e5b-48bb-86e5-c40e5be07d29.mp4

I then did some binary searching and confirmed this problem has actually been with us for a while. Specifically, I was first able to repro it at Brim commit f4edcbe, which is associated with #1290 (so, this goes back a _couple_ GA releases, to before `v0.22.0`) when a lot of the code was moved around in the repo to make way for the PPL licensing changes. Perhaps that caused many more source files to be "watched" than before?

Since it's been with us for a while and nobody from the community has yet complained, it seems it's not a crisis. However, assuming we realize the dream of having community members start making improvements to the code, and also knowing that many of our most active community members happen to be running Linux, it might be good if we can do something to improve here. A few things that come to mind:

1. If the root cause is, indeed, that a very high number of source files are being "watched", can we confirm that they definitely all need to be? If we could decrease the count to a value under the limit (hopefully leaving significant headroom so this doesn't sneak up on us again), that would seem ideal.

2. If we can't reduce the number of files being "watched", is there a way to effectively increase the limit without requiring the user to modify the sysctl setting? I'm assuming this is a long shot, but I seem to recall the Go devs were successful in having our code effectively "increase its own limits" for some settings at process start time, so I figured I'd at least check.

3. If we can't make any improvements via the above or other ideas, then it seems we should just update the [contributing doc](https://github.com/brimdata/brim/blob/main/CONTRIBUTING.md) to disclose the importance of this setting on Linux so it doesn't catch developers by surprise.

**Comment by jameskerr** [comment]
It looks like we're watching all the files in the node_modules directory which is not needed. I think if we find a way to ignore those, we should be good to go.

**Comment by philrz** [comment]
For the first time in a long time I happened to try starting Zui in Dev mode on Linux (commit a231ce0)  and I had none of the problems described above. While I don't know precisely which changes made this possible, we've definitely had a lot of code reorganization in the repo in the past couple years so I'm not surprised that things have improved. Therefore I'm going to go ahead and close this one.
