### ISSUE TITLE
Empty Pool Display

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2198]
When a pool has no data in it, we need to provide a message saying so and some instructions on how to load data in it. 

This is what it looks like now.
<img width="1792" alt="Screen Shot 2022-02-21 at 11 31 48 AM" src="https://user-images.githubusercontent.com/3460638/155016455-83b876bf-9df5-4d23-97e7-21d1fbb72ba3.png">

**Comment by philrz** [comment]
Verified in Zui commit f1aef59.

The workflow has changed significantly such that empty pools are more clearly presented now. As shown in the attached video, now there's a pool summary page that shows an explicit "This pool is empty" message.

https://github.com/brimdata/zui/assets/5934157/911729da-acbd-414e-88e2-8bc3ab0409ea
