### ISSUE TITLE
Lake URL cut off if too long

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2200]
Add some ellipses or let it scroll.

<img width="369" alt="Screen Shot 2022-02-21 at 11 46 35 AM" src="https://user-images.githubusercontent.com/3460638/155017864-99cd7bf2-856f-42ad-b603-a333bcd077ba.png">

**Comment by philrz** [comment]
Verified in Zui commit f1aef59.

While I'm not certain of the exact commit(s) that fixed it, the attached video shows that now when the lake URL value is too wide to fit in the visible area it's now possible to scroll left/right to see the entire value.

https://github.com/brimdata/zui/assets/5934157/a2f6c684-5ccd-4e52-ae26-c0dfccb8ebde
