### ISSUE TITLE
Zui import error when file path contains Chinese and other wide characters

### ISSUE THREAD

**Issue by burpheart** [brimdata/zui#2723]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://zui.brimdata.io/docs/support/Troubleshooting

**Describe the bug**
[A description of what the bug is]
Zui import error when importing files containing file paths with Chinese and other wide characters
**To Reproduce**
import file name
``` 
⛔1678526411.json

の1678526374.json

中文测试-1678526374 1.json
```
**Expected behavior**
import success

**Desktop Info**
```
{"author":"zui","body":"automatic import of E:\\⛔1678526411.json"} is not a legal HTTP header value
{"author":"zui","body":"automatic import of E:\\の1678526374.json"} is not a legal HTTP header value
{"author":"zui","body":"automatic import of E:\\中文测试-1678526374 1.json"} is not a legal HTTP header value
```
 - OS: Windows
 - Zui Version: 1.0.0

**Comment by philrz** [comment]
Thanks for filing @burpheart. Indeed that's something we'll need to fix.

For ease of repro, I've attached [repro.tgz](https://github.com/brimdata/zui/files/10949145/repro.tgz) that has files with these names that trigger the problem. It looks like this is where we're getting tripped up:

https://github.com/brimdata/zui/blob/03153c8e377ca49c97077fa2deaa6d32c0da8474/packages/zealot/src/client/client.ts#L57

In a healthy data load that makes it past this spot, the headers look something like this:

```
POST /pool/0x109a722c5a256e630f5198f8717c4a7ca967d979/branch/main HTTP/1.1
Zed-Commit: {"author":"zui","body":"automatic import of /Users/phil/Desktop/sample.zng"}
Accept: application/x-zjson
Content-Type: 
User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
Accept-Encoding: gzip,deflate
Connection: close
Host: localhost:9867
Transfer-Encoding: chunked
```

So in this case it would try to instead include something like `"body": "automatic import of /Users/phil/Desktop/中文测试-16785263741.json"`. I'm not sure which is the definitive statement of this in a the appropriate RFC, but general web searches make it clear that there's limitations on what characters can be present in an HTTP header value. Therefore I assume we need to do some kind of encoding if we want to continue to use headers to transport data such as these filenames that may contain such characters.

It seems we might want to audit our other clients (Python, Go, etc.) to see if we make similar assumptions about what could be transported in headers.

**Comment by philrz** [comment]
@nwt pointed out that the best way to handle this would be to apply `\u` escaping (as can be demo'ed in tools like https://www.freeformatter.com/json-escape.html) before putting the data into the header. Using this approach with the [load example from the Zed API docs](https://zed.brimdata.io/docs/lake/api#load-data):

```
$ zed create inventory
pool created: inventory 2N1FV4M42H9JqG7lteZHzQiavZs

$ zed use inventory
Switched to branch "main" on pool "inventory"

$ curl -X POST \
     -H 'Accept: application/json' \
     -H 'Content-Type: application/json' \
     -H 'Zed-Commit: {"author":"zui","body":"automatic import of \u4E2D\u6587\u6D4B\u8BD5-16785263741.json"}' \
     -d '{"product": {"serial_number": 12345, "name": "widget"}, "warehouse": "chicago"}
         {"product": {"serial_number": 12345, "name": "widget"}, "warehouse": "miami"}
         {"product": {"serial_number": 12346, "name": "gadget"}, "warehouse": "chicago"}' \
     http://localhost:9867/pool/inventory/branch/main

$ zed log
commit 2N1FeGhybzxxWkZqtyg4eLPtRxi (HEAD -> main)
Author: zui
Date:   2023-03-14T19:56:14Z

    automatic import of 中文测试-16785263741.json
```

**Comment by philrz** [comment]
Verified in Zui commit f835e04.

As shown in the attached video, now all the files with the wide characters can be successfully loaded into Zui.

https://user-images.githubusercontent.com/5934157/229187950-e8a29735-4578-43c1-9fde-381bff04cf71.mp4

Thanks @jameskerr!
