### ISSUE TITLE
Export to Pool Workflow

### ISSUE THREAD

**Issue by jameskerr** [brimdata/zui#2769]
It would be very good to be able to export the results of a query to be loaded into a new pool. The load operator would do this already. The Zui UI could be different by letting you confirm with a click that you want to the load to happen. It might feel safer.

A flow could be like so:

1. Click export
2. Click into a pool
3. Select the pool
4. Confirm
5. Execute

**Comment by philrz** [comment]
Verified in Zui commit 1365bbd.

As shown in the attached video, this option is now available once **Export** is selected. A selector is available if the user wants to export to an existing pool, or a new pool can be created with the typical settings like pool name, pool key, and sort direction for the key.

https://github.com/brimdata/zui/assets/5934157/10675348-fd53-4f12-a8a2-3d657683cf02

Thanks @jameskerr!
