### ISSUE TITLE
Instructions on building from source

### ISSUE THREAD

**Issue by lavafroth** [brimdata/zui#2780]
Hi. I wish to build zui from source for non-Debian and non-Ubuntu linux distributions. I'd really appreciate a subsection in the readme or the wiki that describes how to build from source. Thanks!

**Comment by philrz** [comment]
@lavafroth: Thanks for your interest in Zui! https://github.com/brimdata/zui/blob/main/CONTRIBUTING.md includes detail on how to build from source. Let us know if you have any problems.
