### ISSUE TITLE
"Long poll" approach to replace node-pipe

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#2884]
At the time this issue is being filed, Zui is at commit d29e674.

Recent issue #2882 caused the team to reassess `node-pipe`. Indeed, old issue #1165 predicted precisely that problem. Rather than put in more hacks to prolong the life of `node-pipe`, the team reached consensus on moving forward with an approach that was first proposed and rejected back in the day: Zui doing a "long poll" on a new Zed lake API endpoint. This is expected to functionally replace what `node-pipe` is currently doing.

Some notes-to-self for when this is implemented:
* I'll want to test that all the failure scenarios described in #1018 and #534 are handled as well or better than they were with `node-pipe`.
* Also check if the long poll connection closes when a user's computer comes back from suspend/sleep/hibernation.
* I'll need to update the [Remote Zed lakes](https://zui.brimdata.io/docs/advanced/Remote-Zed-Lakes) article since it currently calls attention to the `brimfd` flag that's part of `node-pipe`.

**Comment by nwt** [comment]
#2956 removes the node-pipe dependency so we don't need to implement this.
