### ISSUE TITLE
Added features for Zui

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#2924]
Added features for Zui

1. Searched texts should be displayed as highlights
2. The time spent searching for a query should be written (next to the bar below next to Shapes
3. It is not possible to copy a specific row in the table section. Neither in the table section nor INSPECTOR

The features are not necessary, but they make the program better

Because I use this great tool a lot. That's why there are so many of my requests. And cause trouble for the programming team

**Comment by SoftTools59654** [comment]
4 . When the command from * is used for general search of all files

When the item is found. It is not possible to find out which pool this found data belongs to

If there is an option to show which pool the found data belongs to, I think it would be appropriate

**Comment by philrz** [comment]
@SoftTools59654: Thanks for the suggestions. We try to avoid tracking multiple ideas in the same issue, so I'll point to open issues below that cover each of your ideas and then close this one.

> Searched texts should be displayed as highlights

I've opened #2929 to capture this one. As noted there, you may also want to see #2574 as I imagine that's likely to arrive sooner.

> The time spent searching for a query should be written (next to the bar below next to Shapes)

This is now tracked in #2930.

>  When the command from * is used for general search of all files
> When the item is found. It is not possible to find out which pool this found data belongs to
> If there is an option to show which pool the found data belongs to, I think it would be appropriate

This is now tracked in #2931.

---

Also, thanks for mentioning that you're enjoying the tools. By your mention of a "programming team" it sounds like your bug reports and feature requests represent the interests of a larger organization. When possible we like to talk to users of the technology (especially larger teams) to better understand their wider use cases as it helps us assign priority to the issues. If you or someone from your organization would be able to participate in a Zoom call to discuss please contact us either by emailing support@brimdata.io or joining our [community Slack](https://www.brimdata.io/join-slack/) and messaging me directly `@Phil`. Thanks!
