### ISSUE TITLE
Searching the text of each line

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#3013]
Searching the text of each line (searched text written in each line)

I want to search each line of text that is written in the same way separately, not a combination of two lines.

But for example, I wrote **Musical** in the first line and **Comedy** in the second line
  The result is 8 items that are displayed when both options are present in the text. While Musical alone has 14 cases and Comedy has 25 cases, I want it to search these two separately, and Musical and Comedy separately, not a combination of them.

Maybe this feature exists, but I don't know

![image](https://github.com/brimdata/zui/assets/150426297/7d78cc11-0b30-4098-b059-ab6ff7904719)

![image](https://github.com/brimdata/zui/assets/150426297/a62d4d49-49bf-4a8b-8bbc-0c828258b9a0)

![image](https://github.com/brimdata/zui/assets/150426297/afde9844-ba03-4d48-8d9c-5fc89cf08356)

**Comment by philrz** [comment]
@SoftTools59654: If I understand your question correctly, I think you're just looking for the logical operator `or`. See the [search expression docs on boolean logic](https://zed.brimdata.io/docs/language/search-expressions#boolean-logic) for details.

To illustrate using an example we can both see, I'm using the publicly-available test data from https://gist.github.com/jheer/4dee9b65d5f4cab64235e28d0e4010dc.

With this data, searching for just "Musical" finds 54 values. (BTW, from your screenshots and the numbers you're citing it looks like you're maybe confusing the "Shapes" count as if that's the number of values in the query result. The number of values in the query result is shown at the bottom as I've circled in this first screenshot.)

![image](https://github.com/brimdata/zui/assets/5934157/f774dcaf-496d-4896-8526-e50f9acaeff8)

Searching for "Comedy" with this data finds 849 values.

![image](https://github.com/brimdata/zui/assets/5934157/3536b345-5204-4e46-a6b6-e922131154bb)

Entering both search terms on separate lines like you did in your screenshot has the same effect as if they'd been entered on the same line: As that doc I linked to above explains, there's an implicit `and` between these search terms. So in this data, there happens to be only one value that matches on both "Musical" and "Comedy".

![image](https://github.com/brimdata/zui/assets/5934157/0b476de5-0620-4780-8591-818c32bbe50c)

Finally, by using `or`, you can find in a single search all the values that match on either or both of those search terms. You can put it all on one line or split it across multiple lines like I've done here to be similar to your original screenshot.

![image](https://github.com/brimdata/zui/assets/5934157/dd836816-db38-4734-bdfd-24bd5f6c588a)

Let me know if that answers your question.

**Comment by SoftTools59654** [comment]
Thank

It was my mistake and I should have carefully checked the explanations

Thank you for your complete answer. I hope you will put the things you taught me in the form of images on the site, the image is much better
