### ISSUE TITLE
Adding e+06 character to decimal numbers

### ISSUE THREAD

**Issue by SoftTools59654** [brimdata/zui#3020]
Adding e+06 character to decimal numbers

There is no such character in the original file. After import, this number and character is added, and even in the search output, this character is also present

Decimal numbers are also correct conversions
1382985.12
Output and display number
1.38298512e+06

![image](https://github.com/brimdata/zui/assets/150426297/3aac1e89-97c9-4cfe-8b31-88276904c08e)

**Comment by philrz** [comment]
@SoftTools59654: This would not normally be considered a bug, as it reflects the common practice of printing large numbers using [scientific notation](https://en.wikipedia.org/wiki/Scientific_notation), specifically [E notation](https://en.wikipedia.org/wiki/Scientific_notation#E_notation) in this case. Many other tools do much the same, though they vary as to how large numbers may become before they choose to switch to this format, e.g., Python:

```
$ python3
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(138298500000000000.12)
1.382985e+17
```

Most tools that accept numeric input accept this format. Can you describe a specific problem this poses for your workflow?

**Comment by philrz** [comment]
As scientific notation is very common presentation in tools like this and we've not seen more user response since the most recent update here, I'm going to go ahead and close this issue.
