### ISSUE TITLE
Add indication of the size of a Pool

### ISSUE THREAD

**Issue by siskojr** [brimdata/zui#710]
**Request**
As a User I want to see the size of a Pool so that I can understand it's disk consumption.

**Rationale**
As part of new functionality we want to support pcap files that are compressed. We require to store the file un-compressed so that export to pcap works.

Typical gzip ratios vary from 3X-6X and can lead to significant difference in disk utilization. We want to let the user know about the size a space is occupying. This will also provide a clue to deduce that the pcap files are stored in un-compressed format.

Example of UX option:

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/dbf3f6f4-a077-46f7-9f22-53f6a4856952)

**Comment by alfred-landrum** [comment]
@siskojr : we discussed this as part of handling compressed pcaps, not log ingest, so I'm removing it from the log ingest epic.

**Comment by philrz** [comment]
A lot has changed since this issue was opened. However, the spirit of showing the size of a pool is still very much a good idea. #2755 has been opened to collect up the current ideas for including this as part of a redesign, so I'll close this particular issue as a duplicate.
