### ISSUE TITLE
zq auto-update is not always fifo

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zui#800]
It looks like two zq PRs were merged in quick succession (note CommitDate):
```
commit cb2f9de67045483795c264899b84caa6b55fb97c (origin/master, origin/HEAD)
Author:     Henri DF <henridf@gmail.com>
AuthorDate: Wed May 20 18:27:40 2020 +0200
Commit:     GitHub <noreply@github.com>
CommitDate: Wed May 20 18:27:40 2020 +0200

    zar: fix index path logged on stdout (#805)

commit 5bad06419f58c6558023c146021aa5eaaa77df83
Author:     aswan <aswan@looky.cloud>
AuthorDate: Wed May 20 11:27:18 2020 -0500
Commit:     GitHub <noreply@github.com>
CommitDate: Wed May 20 11:27:18 2020 -0500

    Fix subnet searches (#807)

    When search was reworked in #597, subnet searches (i.e., a search term
    that is just a network such as "192.168.1.0/24") were broken.  Fix them
    here and add a test case.
```
`5bad06419f58c6558023c146021aa5eaaa77df83` spun off [this](https://github.com/brimsec/zq/runs/693554167?check_suite_focus=true) "notify Brim" run completed Wed, 20 May 2020 16:27:32 GMT.
`cb2f9de67045483795c264899b84caa6b55fb97c` spun off [this](https://github.com/brimsec/zq/runs/693555093?check_suite_focus=true) "notify Brim" run, started Wed, 20 May 2020 16:27:52 GMT. You can see there was no overlap.

On the "Advance ZQ" side, we see that the *later* branch's [job](https://github.com/brimsec/brim/runs/693555630?check_suite_focus=true) started first, at Wed, 20 May 2020 16:28:02 GMT. A few seconds later, the *earlier* branch's [job](https://github.com/brimsec/brim/runs/693554663?check_suite_focus=true) started (Wed, 20 May 2020 16:28:11 GMT).

1. This means jobs can be queued up but Github doesn't run them fifo. This is an unexpected behavior, not in line with other CI systems' defaults, like Jenkins.
1. Turnstyle was ineffective in blocking one job.

Even if turnstyle had blocked properly, zq would have likely been pointing to the earlier commit when all is said and done.

**Comment by philrz** [comment]
Thanks to the changes in #2665 we moved on from turnstyle a long time ago and we've not had these kinds of concurrency problems with the replacement solution. Closing this issue.
